# e:\workspace\autocaller\scripts\models.py
"""
Data models for contact form schemas, contact page analysis, and visual verification results.
Defines the Pydantic structure for responses generated by the Gemini API.
"""

from pydantic import BaseModel, Field
from typing import List, Optional

class ContactFormField(BaseModel):
    """Represents a single input field or element within a website's contact form."""
    name: Optional[str] = Field(
        description="The 'name' attribute of the input/textarea field, or a descriptive placeholder if missing."
    )
    type: Optional[str] = Field(
        description="The type of the field (e.g., text, email, tel, textarea, select, checkbox, radio)."
    )
    label: Optional[str] = Field(
        description="The label or visual text associated with this field in the UI."
    )
    required: bool = Field(
        description="Whether the field is marked as required/mandatory."
    )
    placeholder: Optional[str] = Field(
        description="The placeholder text displayed in the field, if any."
    )

class ContactFormDetails(BaseModel):
    """Represents the structure, HTTP method, action endpoint, and fields of a contact form."""
    action: Optional[str] = Field(
        description="The action URL/endpoint of the form, if any."
    )
    method: Optional[str] = Field(
        description="The HTTP method of the form submission (e.g., POST, GET)."
    )
    fields: List[ContactFormField] = Field(
        description="List of all input and message fields present inside the contact form."
    )

class ContactPageAnalysis(BaseModel):
    """Represents the contact information and form structure parsed from a contact page's HTML."""
    email: Optional[str] = Field(
        description="Any contact or booking email address found on the page, or null if none."
    )
    phone: Optional[str] = Field(
        description="Any contact telephone number found on the page (preferably French format), or null."
    )
    has_form: bool = Field(
        description="Whether a contact/inquiry form exists on the page."
    )
    form_details: Optional[ContactFormDetails] = Field(
        description="Detailed structure of the contact form if one exists, else null."
    )

class VisualFormVerification(BaseModel):
    """Represents the visual QA audit results cross-referencing screenshots with HTML drafts."""
    form_is_visible: bool = Field(
        description="True if the contact form is visible in the screenshot image."
    )
    submit_button_is_visible: bool = Field(
        description="True if the submit/send/confirm button for the form is visible in the screenshot."
    )
    is_draft_accurate: bool = Field(
        description="True if the draft JSON matches the screenshot perfectly without corrections."
    )
    extracted_email: Optional[str] = Field(
        description="Any contact email address visible on the page (e.g., in text, headers, footers). Null if not visible."
    )
    extracted_phone: Optional[str] = Field(
        description="Any phone number visible on the page (preferably French format). Null if not visible."
    )
    verified_form_details: Optional[ContactFormDetails] = Field(
        description="The corrected/verified form schema matching the screenshot. Null if no form is visible."
    )
    verification_notes: Optional[str] = Field(
        description="Explanation of corrections made, mismatches found, or reasons for verification failure."
    )

class VenueCandidate(BaseModel):
    """Represents a proposed new wedding venue sourced via grounded Gemini search."""
    name: str = Field(
        description="Official venue name, e.g. 'Château de Canisy'."
    )
    city: str = Field(
        description="City or commune where the venue is located."
    )
    department: str = Field(
        description="Two-digit French department code as a string, e.g. '14' or '04'."
    )
    region: str = Field(
        description="Full official French region name, e.g. 'Normandie'."
    )
    type: str = Field(
        description="Venue type, exactly one of: château, domaine, salle, ferme, manoir, atypique."
    )
    website: str = Field(
        description="Official venue website URL (never a directory listing or social media page)."
    )
